document.addEventListener("DOMContentLoaded", function () {
    const fortunes = [
        "You will find a sock with no match.",
        "Beware of sandwiches that whisper.",
        "A cat will judge you silently today.",
        "Your lucky number is pi.",
        "The wind knows your secrets.",
        "You will discover a new shade of blue.",
        "A mysterious package will arrive soon.",
        "You will invent a new dance move.",
        "Your plants will start talking to you.",
        "You will find a hidden talent for yodeling.",
        "A surprise is waiting in your fridge.",
        "You will become friends with a squirrel.",
        "Your next idea will change the world.",
        "You will master the art of napping.",
        "A rainbow will appear when you least expect it.",
        "You will find joy in the little things today.",            
        "Your laughter will be contagious.",
        "You will stumble upon a secret garden.",
        "A new hobby will bring you great happiness.",
        "You will make a discovery in your own backyard.",
        "Your creativity will shine brightly today.",
        "You will find inspiration in an unexpected place.",
        "A kind stranger will brighten your day.",
        "You will learn something new about yourself.",
        "Your dreams will guide you to new adventures.",
        "You will find beauty in the ordinary.",
        "A spontaneous trip is on the horizon.",
        "You will create something amazing with your hands.",
        "Your sense of humor will lead to new friendships.",
        "You will find peace in nature today.",
        "A forgotten memory will bring you joy.",
        "You will have a breakthrough in your work.",
        "Your optimism will inspire those around you.",
        "You will discover a new favorite book.",
        "A delicious meal is in your future.",
        "You will find clarity in a confusing situation.",
        "Your kindness will come back to you tenfold.",
        "You will have a moment of serendipity.",
        "A new opportunity will present itself soon.",
        "You will find strength in unexpected places.",
        "Your intuition will lead you to success.",
        "You will make a positive impact on someone's life.",
        "A joyful surprise is coming your way.",
        "You will find balance in your daily routine.",
        "Your adventurous spirit will take you far.",
        "You will discover a new favorite song.",
        "A moment of clarity will change your perspective.",
        "You will find joy in helping others.",
        "Your dreams are closer than you think.",
        "A new friendship will blossom soon.",
        "You will find success in your creative endeavors.",
        "Your positive energy will attract good things.",
        "You will have a memorable experience today.",
        "A new skill will open doors for you.",
        "You will find happiness in the little things.",
        "Your courage will lead you to new heights.",
        "A moment of kindness will brighten your day.",
        "You will discover a hidden talent.",
        "Your enthusiasm will inspire those around you.",
        "You will find joy in unexpected places.",
        "A new adventure is on the horizon.",
        "You will make a difference in someone's life today.",
        "Your creativity will lead to exciting opportunities.",
        "You will find peace in the present moment.",
        "A new perspective will bring clarity to your life.",
        "You will have a breakthrough in your personal growth.",
        "Your optimism will attract positive experiences.",
        "You will find success in your endeavors.",
        "A joyful surprise is waiting for you.",
        "You will discover a new passion.",
        "Your kindness will create lasting connections.",
        "You will find inspiration in everyday moments.",
        "A new chapter in your life is about to begin.",            
    ];

    const fortuneBtn = document.getElementById("fortuneButton");
    const fortuneDiv = document.getElementById("fortune");

    if (!fortuneBtn || !fortuneDiv) return;

    fortuneBtn.addEventListener("click", function () {
        const randomIndex = Math.floor(Math.random() * fortunes.length);
        const selectedFortune = fortunes[randomIndex];
        fortuneDiv.textContent = selectedFortune;
    });
});